// Generated by dts-bundle-generator v6.5.0

export declare var Tween: {
  Linear: (t: number, b: number, c: number, d: number) => number;
  Quad: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
  Cubic: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
  Quart: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
  Quint: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
  Sine: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
  Expo: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
  Circ: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
  Elastic: {
    easeIn: (
      t: number,
      b: number,
      c: number,
      d: number,
      a?: number | undefined,
      p?: number | undefined
    ) => number;
    easeOut: (
      t: number,
      b: number,
      c: number,
      d: number,
      a?: number | undefined,
      p?: number | undefined
    ) => number;
    easeInOut: (
      t: number,
      b: number,
      c: number,
      d: number,
      a?: number | undefined,
      p?: number | undefined
    ) => number;
  };
  Back: {
    easeIn: (
      t: number,
      b: number,
      c: number,
      d: number,
      s?: number | undefined
    ) => number;
    easeOut: (
      t: number,
      b: number,
      c: number,
      d: number,
      s?: number | undefined
    ) => number;
    easeInOut: (
      t: number,
      b: number,
      c: number,
      d: number,
      s?: number | undefined
    ) => number;
  };
  Bounce: {
    easeIn: (t: number, b: number, c: number, d: number) => number;
    easeOut: (t: number, b: number, c: number, d: number) => number;
    easeInOut: (t: number, b: number, c: number, d: number) => number;
  };
};

export {};
