// Generated by dts-bundle-generator v6.5.0

/**
 *
 * @param x1 控制点1的x坐标
 * @param y1 控制点1的y坐标
 * @param x2 控制点2的x坐标
 * @param y2 控制点2的y坐标
 * @returns 生成由贝塞尔变化的缓动函数
 */
export declare function createBezierEasing(
  x1: number,
  y1: number,
  x2: number,
  y2: number
): (t: number, b: number, c: number, d: number) => number;

export {};
